id: I241FCCB2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:47:37+00:00'
last_modified: '2022-06-09T07:26:15.263272+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25855
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    39A5:
      image_group_id: I1KG25857
      title: Volume 1 of sman sbyor nus pa phyogs bsdus kun gsal me long /
      total_pages: 247
      order: 1
      base_file: 39A5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
