id: P007915
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25855
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    1e4f6eda29284a5dbcdbb9cc97ec92dc:
      image_group_id: I1KG25857
      title: ''
      volume_number: 1
      total_pages: 247
ebook_metadata:
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  sku: P007915
  cover: cover.jpg
  layers:
  - pagination
