id: P007915
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25855
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    9b23078e61ac4c2795d66263a4cfbf03:
      image_group_id: I1KG25857
      title: Volume 1 of sman sbyor nus pa phyogs bsdus kun gsal me long /
      volume_number: 1
      total_pages: 247
      base_file: v001.txt
ebook_metadata:
  title: སྨན་སྦྱོར་ནུས་པ་ཕྱོགས་བསྡུས་ཀུན་གསལ་མེ་ལོང་།
  author: ''
  sku: P007915
  cover: cover.jpg
  layers:
  - pagination
